import {MARKETS,CATEGORIES,BRANDS,COMPARISONS,commerceMeta,articleCommerceLinks,commercePaths,COMMERCE_TAXONOMY_INFO} from './commerce-taxonomy.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=s=>encodeURI(String(s||''));
const safe=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const CODES=['NOV170','NOV188','NOV174','NOV157','NOV177','NOV186','NOV163','NOV153','NOV195','NOV161'];
const CSS=`:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;font-family:Tahoma,Arial,sans-serif;background:#f8fafc;color:#111827}.w{width:min(1180px,92%);margin:auto}.hero{padding:46px 0;background:linear-gradient(135deg,#111827,#312e81);color:#fff}.hero h1{font-size:clamp(30px,5vw,50px);line-height:1.35;margin:14px 0}.hero p{color:#e5e7eb;line-height:1.9;max-width:850px}.crumbs,.chips{display:flex;gap:8px;flex-wrap:wrap}.crumbs a{color:#ddd6fe}.chips a{display:inline-block;background:#fff;color:#111827;text-decoration:none;border:1px solid #e5e7eb;border-radius:999px;padding:9px 13px;font-weight:800}.section{padding:30px 0}.section h2{font-size:clamp(24px,3vw,32px);margin:0 0 12px}.lead{color:#667085;line-height:1.9;max-width:900px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:18px;min-width:0}.card h3{font-size:19px;line-height:1.55;margin:9px 0}.card a{color:#111827;text-decoration:none}.card p{color:#667085;line-height:1.8}.card small{color:#6d28d9;font-weight:800}.read{color:#6d28d9!important;font-weight:900}.coupon{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center;background:#fffbeb;border:1px solid #fde68a;border-radius:20px;padding:20px;margin:24px 0}.code{display:inline-block;background:#111827;color:#fff;border-radius:10px;padding:7px 11px;font-weight:900;letter-spacing:1px}.cta{display:inline-block;background:#facc15;color:#111827!important;text-decoration:none;font-weight:900;padding:13px 16px;border-radius:12px}.check{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.check div{background:#fff;border:1px solid #e5e7eb;border-radius:15px;padding:16px;line-height:1.85}.table{width:100%;border-collapse:collapse;background:#fff}.table th,.table td{border:1px solid #e5e7eb;padding:12px;text-align:right;vertical-align:top}.spider{padding:28px 0;background:#111827;color:#fff}.spider .chips a{border:0}.empty{background:#fff;border:1px dashed #cbd5e1;border-radius:18px;padding:20px;color:#64748b}.stats{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.stats span{background:rgba(255,255,255,.1);padding:7px 10px;border-radius:999px;font-size:13px}@media(max-width:920px){.grid{grid-template-columns:1fr 1fr}.grid4{grid-template-columns:1fr 1fr}}@media(max-width:640px){.grid,.grid4,.check,.coupon{grid-template-columns:1fr}.hero{padding:34px 0}.cta{text-align:center}}`;

async function latest(env){try{const o=await env.CONTENT_FINAL?.get('bulk/latest.json');return o?await o.json():{articles:[]}}catch{return {articles:[]}}}
function codeFor(s){let n=0;for(const c of String(s||''))n=(n*33+c.charCodeAt(0))>>>0;return CODES[n%CODES.length]}
function card(a){return `<article class="card"><small>${a.country==='AE'?'الإمارات':'السعودية'} · ${esc(a.intentLabel||a.intent||'دليل')}</small><h3><a href="/articles/${enc(a.slug)}">${esc(a.title||a.primaryKeyword||a.slug)}</a></h3><p>${esc((a.metaDescription||'').slice(0,180))}</p><a class="read" href="/articles/${enc(a.slug)}">اقرأ الدليل ←</a></article>`}
function marketArticles(all,m){return (all||[]).filter(a=>a?.slug&&a.indexable!==false&&a.country===MARKETS[m].country)}
function rowsBy(all,m,pred,limit=24){return marketArticles(all,m).filter(pred).slice(0,limit)}
function breadcrumbs(m,parts=[]){let html=`<div class="crumbs"><a href="/">الرئيسية</a><span>←</span><a href="/${m}/categories">أقسام ${MARKETS[m].name}</a>`;for(const p of parts)html+=`<span>←</span>${p.path?`<a href="${p.path}">${esc(p.label)}</a>`:`<span>${esc(p.label)}</span>`}`;return html+'</div>'}
function coupon(m,key,label){const mk=MARKETS[m],code=codeFor(m+key);return `<aside class="coupon"><div><small>كود من قائمة الموقع للتجربة</small><h2>جرّب <span class="code">${code}</span> مع ${esc(label)}</h2><p class="lead">لا نثبت نسبة خصم أو أهلية غير موثقة. ثبّت المنتج والبائع والسلة، جرّب الكود، ثم اجعل إجمالي نون النهائي هو المرجع.</p></div><a class="cta" href="${mk.noon}" rel="noopener external sponsored">فتح ${mk.name}</a></aside>`}
function categoryGrid(m){return `<div class="grid4">${Object.entries(CATEGORIES).map(([k,c])=>`<article class="card"><h3><a href="/${m}/category/${k}">${esc(c.label)}</a></h3><p>${esc(c.desc)}</p><a class="read" href="/${m}/category/${k}">افتح القسم ←</a></article>`).join('')}</div>`}
function brandGrid(m){return `<div class="grid4">${Object.entries(BRANDS).map(([k,b])=>`<article class="card"><h3><a href="/${m}/brand/${k}">${esc(b.label)}</a></h3><p>${Object.values(b.models).map(x=>esc(x.label)).join(' · ')}</p><a class="read" href="/${m}/brand/${k}">صفحة البراند ←</a></article>`).join('')}</div>`}
function spider(m,current=''){const featured=['mobiles','electronics','computers','gaming','home-kitchen','beauty','shoes','bags','sports','automotive'];return `<section class="spider"><div class="w"><h2>تحرك داخل شبكة الموقع</h2><div class="chips"><a href="/">الرئيسية</a><a href="/${m}/categories">كل الأقسام</a>${featured.filter(k=>k!==current).map(k=>`<a href="/${m}/category/${k}">${esc(CATEGORIES[k].label)}</a>`).join('')}<a href="/blog">كل المقالات</a></div></div></section>`}
function head(origin,path,title,desc,rows=[],extra=[]){const crumbs=path.split('/').filter(Boolean),graph={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage','@id':origin+path+'#page',url:origin+path,name:title,description:desc,inLanguage:'ar',mainEntity:{'@type':'ItemList',numberOfItems:rows.length,itemListElement:rows.map((a,i)=>({'@type':'ListItem',position:i+1,url:origin+'/articles/'+enc(a.slug),name:a.title||a.slug}))},{'@type':'BreadcrumbList',itemListElement:crumbs.map((x,i)=>({'@type':'ListItem',position:i+1,name:i===crumbs.length-1?title:x,item:origin+'/'+crumbs.slice(0,i+1).join('/')}))},...extra]};return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | كوبونات نون</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(origin+path)}"><script type="application/ld+json">${safe(graph)}</script><style>${CSS}</style>`}
function response(html,kind,extra={}){return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=90,s-maxage=300','x-commerce-network':'v2','x-commerce-kind':kind,...extra}})}

async function directory(m,origin,env){const mk=MARKETS[m];if(!mk)return null;const all=(await latest(env)).articles||[],rows=marketArticles(all,m).slice(0,18),path=`/${m}/categories`,title=`أقسام ${mk.name}`,desc=`دليل منظم لأقسام ${mk.name}: من الجوالات والإلكترونيات إلى الأحذية والحقائب والبيت والجمال، مع روابط مباشرة للمقالات والكوبونات.`;return response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${breadcrumbs(m)}<h1>${title}</h1><p>${desc}</p><div class="stats"><span>${Object.keys(CATEGORIES).length} قسم</span><span>${Object.keys(BRANDS).length} براند جوالات</span><span>${COMMERCE_TAXONOMY_INFO.models} عائلة موديلات</span></div></div></header><main class="w"><section class="section"><h2>كل الأقسام</h2>${categoryGrid(m)}</section>${coupon(m,'directory','أي قسم')}<section class="section"><h2>أحدث الأدلة في ${mk.label}</h2><div class="grid">${rows.map(card).join('')}</div></section></main>${spider(m)}</body></html>`,'directory')}

async function categoryPage(m,key,origin,env){const mk=MARKETS[m],c=CATEGORIES[key];if(!mk||!c)return null;const all=(await latest(env)).articles||[],rows=rowsBy(all,m,a=>commerceMeta(a).categoryKey===key,30),path=`/${m}/category/${key}`,title=`${c.label} على ${mk.name}`,desc=`${c.desc} هذه الصفحة تربط القسم بمقالات القرار والكوبون والبراندات والصفحة الرئيسية داخل شبكة داخلية واضحة.`;return response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${breadcrumbs(m,[{label:c.label}])}<h1>${title}</h1><p>${desc}</p><div class="chips"><a href="/${m}/categories">كل الأقسام</a><a href="/topics/buying-guides">أدلة الشراء</a><a href="/topics/coupon-help">مشاكل الكوبونات</a></div></div></header><main class="w">${coupon(m,key,c.label)}<section class="section"><h2>كيف تستخدم صفحة ${c.label}؟</h2><div class="check"><div><strong>1. حدد الاستخدام</strong><br>ابدأ بما تحتاجه من المنتج، وليس بالكوبون.</div><div><strong>2. ثبت المواصفات</strong><br>قارن نفس السعة أو المقاس أو النسخة قبل مقارنة السعر.</div><div><strong>3. راجع البائع</strong><br>الإرجاع والضمان والشحن جزء من القرار النهائي.</div><div><strong>4. اختبر الكود</strong><br>جرّب الكود بعد تثبيت السلة وقارن الإجمالي النهائي.</div></div></section>${key==='mobiles'?`<section class="section"><h2>براندات الجوالات</h2><p class="lead">من كل براند تصل إلى عائلات الموديلات ثم المقارنات والمقالات المرتبطة.</p>${brandGrid(m)}</section>`:''}<section class="section"><h2>مقالات ${c.label}</h2>${rows.length?`<div class="grid">${rows.map(card).join('')}</div>`:'<div class="empty">المحتوى المتخصص لهذا القسم يتوسع تلقائيًا مع المقالات التي تجتاز بوابة الجودة.</div>'}</section><section class="section"><h2>أقسام مرتبطة</h2>${categoryGrid(m)}</section></main>${spider(m,key)}</body></html>`,'category',{'x-commerce-category':key})}

async function brandPage(m,key,origin,env){const mk=MARKETS[m],b=BRANDS[key];if(!mk||!b)return null;const all=(await latest(env)).articles||[],rows=rowsBy(all,m,a=>commerceMeta(a).brandKey===key,24),path=`/${m}/brand/${key}`,title=`${b.label} على ${mk.name}`,desc=`بوابة ${b.label} على ${mk.name}: عائلات الأجهزة، أدلة الاختيار، المقارنات، الكوبون وروابط المقالات المرتبطة.`;const models=Object.entries(b.models).map(([modelKey,x])=>`<article class="card"><small>عائلة موديلات</small><h3><a href="/${m}/model/${key}/${modelKey}">${esc(x.label)}</a></h3><p>صفحة مخصصة للمقالات والمقارنات المتعلقة بعائلة ${esc(x.label)} بدون تثبيت مواصفات أو أسعار متغيرة.</p><a class="read" href="/${m}/model/${key}/${modelKey}">افتح العائلة ←</a></article>`).join('');const comps=Object.entries(COMPARISONS).filter(([,c])=>c.a===key||c.b===key).map(([k,c])=>`<article class="card"><h3><a href="/${m}/compare/${k}">${esc(c.title)}</a></h3><p>إطار مقارنة قرار الشراء، لا جدول مواصفات ثابت.</p><a class="read" href="/${m}/compare/${k}">افتح المقارنة ←</a></article>`).join('');return response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${breadcrumbs(m,[{label:'الجوالات',path:`/${m}/category/mobiles`},{label:b.label}])}<h1>${title}</h1><p>${desc}</p></div></header><main class="w">${coupon(m,'brand-'+key,b.label)}<section class="section"><h2>عائلات ${b.label}</h2><div class="grid">${models}</div></section><section class="section"><h2>مقارنات مرتبطة</h2><div class="grid">${comps||'<div class="empty">ستضاف المقارنات المناسبة هنا.</div>'}</div></section><section class="section"><h2>مقالات ${b.label}</h2>${rows.length?`<div class="grid">${rows.map(card).join('')}</div>`:'<div class="empty">المقالات المتخصصة ستظهر تلقائيًا بمجرد وجود تطابق واضح مع البراند.</div>'}</section><section class="section"><h2>براندات أخرى</h2>${brandGrid(m)}</section></main>${spider(m,'mobiles')}</body></html>`,'brand',{'x-commerce-brand':key})}

async function modelPage(m,brandKey,modelKey,origin,env){const mk=MARKETS[m],b=BRANDS[brandKey],model=b?.models?.[modelKey];if(!mk||!b||!model)return null;const all=(await latest(env)).articles||[],rows=rowsBy(all,m,a=>{const meta=commerceMeta(a);return meta.brandKey===brandKey&&meta.modelKey===modelKey},24),path=`/${m}/model/${brandKey}/${modelKey}`,title=`${b.label} ${model.label} على ${mk.name}`,desc=`صفحة عائلة ${model.label} داخل ${b.label}: أدلة شراء ومقارنة وبائع وكوبون وروابط لمقالات مرتبطة، بدون ادعاء مواصفات أو أسعار ثابتة.`;return response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${breadcrumbs(m,[{label:'الجوالات',path:`/${m}/category/mobiles`},{label:b.label,path:`/${m}/brand/${brandKey}`},{label:model.label}])}<h1>${title}</h1><p>${desc}</p></div></header><main class="w">${coupon(m,'model-'+brandKey+'-'+modelKey,`${b.short} ${model.label}`)}<section class="section"><h2>ما الذي تقارنه داخل ${model.label}؟</h2><div class="check"><div>السعة والنسخة الإقليمية وحالة الجهاز قبل السعر.</div><div>البائع والضمان وسياسة الإرجاع وموعد الشحن.</div><div>السعر النهائي لنفس السلة بعد تجربة الكود.</div><div>الاحتياج الفعلي: تصوير أو ألعاب أو عمل أو استخدام يومي.</div></div></section><section class="section"><h2>مقالات ${model.label}</h2>${rows.length?`<div class="grid">${rows.map(card).join('')}</div>`:'<div class="empty">هذه العائلة جاهزة لاستقبال المقالات المتخصصة التي يلتقطها محرك الربط تلقائيًا.</div>'}</section><section class="section"><h2>عائلات أخرى من ${b.label}</h2><div class="grid">${Object.entries(b.models).filter(([k])=>k!==modelKey).map(([k,x])=>`<article class="card"><h3><a href="/${m}/model/${brandKey}/${k}">${esc(x.label)}</a></h3><a class="read" href="/${m}/model/${brandKey}/${k}">افتح العائلة ←</a></article>`).join('')}</div></section></main>${spider(m,'mobiles')}</body></html>`,'model',{'x-commerce-brand':brandKey,'x-commerce-model':modelKey})}

async function comparisonPage(m,key,origin,env){const mk=MARKETS[m],c=COMPARISONS[key];if(!mk||!c)return null;const A=BRANDS[c.a],B=BRANDS[c.b],all=(await latest(env)).articles||[],rows=rowsBy(all,m,a=>{const meta=commerceMeta(a);return meta.comparisonKey===key||meta.brandKey===c.a||meta.brandKey===c.b},18),path=`/${m}/compare/${key}`,title=`${c.title} — ${mk.label}`,desc=`مقارنة قرار شراء بين ${A.label} و${B.label} على ${mk.name} مع التركيز على الاستخدام والنسخة والبائع والضمان والإجمالي النهائي، بدون تجميد سعر أو مواصفة متغيرة.`;return response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${breadcrumbs(m,[{label:'الجوالات',path:`/${m}/category/mobiles`},{label:'المقارنات'}])}<h1>${title}</h1><p>${desc}</p><div class="chips"><a href="/${m}/brand/${c.a}">${esc(A.label)}</a><a href="/${m}/brand/${c.b}">${esc(B.label)}</a><a href="/${m}/category/mobiles">كل الجوالات</a></div></div></header><main class="w">${coupon(m,'comparison-'+key,'الجوالات')}<section class="section"><h2>إطار المقارنة</h2><table class="table"><tr><th>المعيار</th><th>${esc(A.label)}</th><th>${esc(B.label)}</th></tr><tr><td>الاستخدام</td><td>حدد أولويتك قبل النظر للسعر.</td><td>قارن نفس الاستخدام ونفس الفئة.</td></tr><tr><td>النسخة والسعة</td><td>ثبت النسخة والسعة وحالة المنتج.</td><td>لا تقارن عرضين مختلفين في الأساس.</td></tr><tr><td>البائع والضمان</td><td>راجع البائع والإرجاع والضمان.</td><td>اجعل خدمة ما بعد الشراء جزءًا من القرار.</td></tr><tr><td>الكوبون</td><td>جرّبه بعد تثبيت السلة.</td><td>قارن الإجمالي النهائي بعد الشحن.</td></tr></table></section><section class="section"><h2>مقالات مرتبطة بالمقارنة</h2>${rows.length?`<div class="grid">${rows.map(card).join('')}</div>`:'<div class="empty">المقالات المقارنة ستظهر هنا تلقائيًا.</div>'}</section></main>${spider(m,'mobiles')}</body></html>`,'comparison',{'x-commerce-comparison':key})}

export async function commerceLanding(path,origin,env){let x=path.match(/^\/(saudi|uae)\/categories$/);if(x)return directory(x[1],origin,env);x=path.match(/^\/(saudi|uae)\/category\/([a-z0-9-]+)$/);if(x)return categoryPage(x[1],x[2],origin,env);x=path.match(/^\/(saudi|uae)\/brand\/([a-z0-9-]+)$/);if(x)return brandPage(x[1],x[2],origin,env);x=path.match(/^\/(saudi|uae)\/model\/([a-z0-9-]+)\/([a-z0-9-]+)$/);if(x)return modelPage(x[1],x[2],x[3],origin,env);x=path.match(/^\/(saudi|uae)\/compare\/([a-z0-9-]+)$/);if(x)return comparisonPage(x[1],x[2],origin,env);return null}

export function commerceArticlePathHtml(a={}){const links=articleCommerceLinks(a);return `<section id="article-commerce-path" aria-label="مسار القسم والبراند"><div class="w"><p style="font-weight:900;color:#6d28d9">استكمل داخل نفس شبكة الشراء</p><h2>القسم والبراند والمقالات المرتبطة</h2><div class="chips">${links.map(x=>`<a href="${x.path}">${esc(x.label)}</a>`).join('')}<a href="/blog">كل المقالات</a><a href="/">الرئيسية</a></div></div></section><style>#article-commerce-path{padding:30px 0;background:#eef2ff;border-top:1px solid #c7d2fe}#article-commerce-path .w{width:min(940px,94%);margin:auto}#article-commerce-path .chips{display:flex;gap:8px;flex-wrap:wrap}#article-commerce-path .chips a{background:#fff;border:1px solid #c7d2fe;border-radius:999px;padding:10px 13px;text-decoration:none;color:#111827;font-weight:800}</style>`}
export function commerceNavHtml(){const keys=['mobiles','electronics','computers','gaming','home-kitchen','beauty','shoes','bags','sports','automotive'];return `<section id="commerce-network-nav" style="padding:30px 0;background:#eef2ff"><div style="width:min(1180px,92%);margin:auto"><h2>تصفح أقسام نون</h2><p style="color:#667085">ابدأ من السوق ثم القسم، وانتقل إلى البراند والموديل والمقال المناسب.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><a href="/saudi/categories">نون السعودية</a><a href="/uae/categories">نون الإمارات</a>${keys.map(k=>`<a href="/saudi/category/${k}">${esc(CATEGORIES[k].label)}</a>`).join('')}</div></div></section><style>#commerce-network-nav a{background:#fff;border:1px solid #c7d2fe;border-radius:999px;padding:10px 13px;text-decoration:none;color:#111827;font-weight:800}</style>`}
export function commerceSitemap(origin){const urls=commercePaths().map(p=>`<url><loc>${esc(origin+p)}</loc></url>`).join('');return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public,max-age=300,s-maxage=300','x-commerce-network':'v2'}})}
export function augmentCommerceSitemap(xml,origin){if(!/<\/sitemapindex>/i.test(xml)||xml.includes('/sitemap-commerce.xml'))return xml;return xml.replace(/<\/sitemapindex>/i,`<sitemap><loc>${origin}/sitemap-commerce.xml</loc></sitemap></sitemapindex>`)}
export {COMMERCE_TAXONOMY_INFO};
