import app from './public-entry.js';
import {commerceLanding,commerceArticlePathHtml,commerceNavHtml,commerceSitemap,augmentCommerceSitemap,COMMERCE_TAXONOMY_INFO} from './commerce-pages-v2.js';
import {commercePaths} from './commerce-taxonomy.js';
import {COMMERCE_GENERATOR_INFO} from './commerce-generator-taxonomy.js';
import {enhanceLandingPage,LANDING_CONTENT_V3} from './landing-content-v3.js';
import {enhanceSpecialtyLanding,LANDING_SPECIALTY_V4} from './landing-specialty-v4.js';
export {ControlPlane,GeneratorControl} from './public-entry.js';

async function r2json(env,key,fallback){try{const o=env.CONTENT_FINAL?await env.CONTENT_FINAL.get(key):null;return o?await o.json():fallback}catch{return fallback}}
const dec=s=>{try{return decodeURIComponent(String(s||''))}catch{return String(s||'')}};
const xmlEsc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function hardened(res){const h=new Headers(res.headers);h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');h.set('x-frame-options','SAMEORIGIN');h.set('permissions-policy','camera=(), microphone=(), geolocation=()');h.set('strict-transport-security','max-age=31536000');return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h})}
function articleMoneyHub(rec={}){const ae=rec.country==='AE',base=ae?'/uae':'/saudi-arabia',country=ae?'الإمارات':'السعودية';return `<aside id="article-money-hub" dir="rtl" style="margin:28px auto;padding:20px;border:1px solid #e5e7eb;border-radius:18px;background:#fff7ed;max-width:1050px;font-family:Tahoma,Arial,sans-serif"><strong>تبحث عن كود نون ${country} قبل الدفع؟</strong><p style="line-height:1.8;color:#475569">انتقل إلى الصفحة الأساسية المخصصة للأكواد بدل الاعتماد على مقال واحد؛ ستجد روابط الأكواد وطريقة التحقق من الأهلية داخل السلة.</p><p><a href="${base}/noon-coupon-code" style="font-weight:900;color:#5b21b6">كود خصم نون ${country}</a> · <a href="${base}/noon-coupon-code-today">أكواد اليوم</a> · <a href="${base}/noon-coupon-code-2026">أكواد 2026</a></p></aside>`}
async function appendArticleCommerce(req,env,res){if(!res.ok||!(res.headers.get('content-type')||'').includes('text/html'))return res;const u=new URL(req.url),slug=decodeURIComponent(u.pathname.split('/').filter(Boolean).pop()||'');if(!slug)return res;const latest=await r2json(env,'bulk/latest.json',{articles:[]});let rec=(latest.articles||[]).find(a=>a?.slug===slug)||null;if(!rec){try{const o=await env.CONTENT_FINAL?.head('articles/'+slug+'.html'),md=o?.customMetadata||{};rec={slug,country:md.c||md.country||'SA',title:md.t?dec(md.t):(md.title||slug),primaryKeyword:md.kw?dec(md.kw):'',categoryKey:md.cat||null,brandKey:md.bk||null,modelKey:md.mk||null,comparisonKey:md.ck||null,landingPath:md.lp||null}}catch{rec={slug,country:'SA',title:slug}}}let html=await res.text();if(!html.includes('id="article-commerce-path"'))html=html.replace(/<\/body>/i,commerceArticlePathHtml(rec||{slug})+'</body>');if(!html.includes('id="article-money-hub"'))html=html.replace(/<\/body>/i,articleMoneyHub(rec||{})+'</body>');const h=new Headers(res.headers);h.delete('content-length');h.set('x-commerce-article-path','v4');h.set('x-money-hub','country-intent-v1');if(rec?.landingPath)h.set('x-commerce-landing-path',rec.landingPath);return new Response(html,{status:res.status,statusText:res.statusText,headers:h})}
async function appendHomeCommerce(req,res){if(!res.ok||!(res.headers.get('content-type')||'').includes('text/html'))return res;const path=new URL(req.url).pathname.replace(/\/+$/,'')||'/';if(!['/','/blog'].includes(path))return res;let html=await res.text();if(!html.includes('id="commerce-network-nav"'))html=html.replace(/<\/body>/i,commerceNavHtml()+'</body>');const h=new Headers(res.headers);h.delete('content-length');h.set('x-commerce-nav','v2');return new Response(html,{status:res.status,statusText:res.statusText,headers:h})}
function mergeCommerceIntoMainSitemap(xml,origin){let text=augmentCommerceSitemap(String(xml||''),origin);if(/<sitemapindex\b/i.test(text)){if(!text.includes('/sitemap-commerce.xml'))text=text.replace(/<\/sitemapindex>/i,`<sitemap><loc>${xmlEsc(origin)}/sitemap-commerce.xml</loc></sitemap></sitemapindex>`);return text}if(/<urlset\b/i.test(text)){const rows=commercePaths().filter(path=>!text.includes(origin+path)).map(path=>`<url><loc>${xmlEsc(origin+path)}</loc></url>`).join('');return text.replace(/<\/urlset>/i,rows+'</urlset>')}return text}
async function augmentSitemapResponse(req,env,res){if(!res.ok||new URL(req.url).pathname!=='/sitemap.xml')return res;const type=(res.headers.get('content-type')||'').toLowerCase();if(!type.includes('xml'))return res;const origin=env.SITE_ORIGIN||new URL(req.url).origin,text=mergeCommerceIntoMainSitemap(await res.text(),origin),h=new Headers(res.headers);h.delete('content-length');h.set('x-commerce-sitemap','v3');h.set('x-commerce-routes',String(COMMERCE_TAXONOMY_INFO.routes));return new Response(text,{status:res.status,statusText:res.statusText,headers:h})}
async function health(env){const latest=await r2json(env,'bulk/latest.json',{articles:[]}),rows=(latest.articles||[]).slice(0,200),explicit=rows.filter(a=>a?.categoryKey&&a?.landingPath),brand=rows.filter(a=>a?.brandKey),model=rows.filter(a=>a?.modelKey),comparison=rows.filter(a=>a?.comparisonKey),high=rows.filter(a=>a?.commercialPriority==='high'),pct=n=>rows.length?Math.round(n/rows.length*100):0,sample=explicit[0]||null;return {ok:true,version:COMMERCE_TAXONOMY_INFO.version,...COMMERCE_TAXONOMY_INFO,generatorTaxonomy:COMMERCE_GENERATOR_INFO,landingContent:LANDING_CONTENT_V3,landingSpecialty:LANDING_SPECIALTY_V4,metadataCoverage:{checked:rows.length,explicit:explicit.length,percent:pct(explicit.length),brand:brand.length,brandPercent:pct(brand.length),model:model.length,modelPercent:pct(model.length),comparison:comparison.length,comparisonPercent:pct(comparison.length),commercialPriorityHigh:high.length,commercialPriorityHighPercent:pct(high.length)},latestExplicitSample:sample?{slug:sample.slug,country:sample.country,categoryKey:sample.categoryKey,brandKey:sample.brandKey||null,modelKey:sample.modelKey||null,comparisonKey:sample.comparisonKey||null,landingPath:sample.landingPath,quality:sample.quality,provider:sample.provider}:null,sitemap:'/sitemap-commerce.xml',mainSitemap:'/sitemap.xml',sitemapDiscovery:'main-index-or-direct-urlset',time:new Date().toISOString()}}

export default{
  async fetch(req,env,ctx){const u=new URL(req.url),path=u.pathname.replace(/\/+$/,'')||'/',origin=env.SITE_ORIGIN||u.origin;if(req.method==='GET'&&path==='/sitemap-commerce.xml')return hardened(commerceSitemap(origin));if(req.method==='GET'&&path==='/api/commerce-health')return new Response(JSON.stringify(await health(env),null,2),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});if(req.method==='GET'){let landing=await commerceLanding(path,origin,env);if(landing){landing=await enhanceLandingPage(path,origin,landing,env);landing=await enhanceSpecialtyLanding(path,origin,landing);return hardened(landing)}}let res=await app.fetch(req,env,ctx);if(req.method==='GET'&&path.startsWith('/articles/'))res=await appendArticleCommerce(req,env,res);res=await appendHomeCommerce(req,res);res=await augmentSitemapResponse(req,env,res);return hardened(res)},
  async scheduled(event,env,ctx){if(app.scheduled)return app.scheduled(event,env,ctx)}
};
export const COMMERCE_ENTRY_INFO={version:9,entry:'commerce-entry',wraps:'public-entry',routes:COMMERCE_TAXONOMY_INFO.routes,articleBacklinks:true,homeNavigation:true,separateShoesAndBags:true,modelFamilyPages:true,explicitGeneratorTaxonomy:COMMERCE_GENERATOR_INFO.version,landingContent:LANDING_CONTENT_V3.version,landingSpecialty:LANDING_SPECIALTY_V4.version,minLandingWords:LANDING_CONTENT_V3.minWords,sitemapDiscovery:'main-index-or-direct-urlset'};
