import app from './commerce-entry.js';
import {APPROVED_COUPON_CODES,replaceUnapprovedCouponTokens} from './approved-coupons.js';
export {ControlPlane,GeneratorControl} from './commerce-entry.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=s=>encodeURI(String(s||''));
let latestCache={at:0,value:null};
async function latestManifest(env){const now=Date.now();if(latestCache.value&&now-latestCache.at<120000)return latestCache.value;try{const o=await env.CONTENT_FINAL?.get('bulk/latest.json');const value=o?await o.json():{articles:[]};latestCache={at:now,value};return value}catch{return latestCache.value||{articles:[]}}}
function scoreRelated(a,rec){let s=0;if(a.country===rec.country)s+=8;if(a.category&&rec.category&&a.category===rec.category)s+=6;if(a.categoryKey&&rec.categoryKey&&a.categoryKey===rec.categoryKey)s+=6;if(a.intent&&rec.intent&&a.intent===rec.intent)s+=4;if(a.brandKey&&rec.brandKey&&a.brandKey===rec.brandKey)s+=4;if(a.modelKey&&rec.modelKey&&a.modelKey===rec.modelKey)s+=3;if(a.comparisonKey&&rec.comparisonKey&&a.comparisonKey===rec.comparisonKey)s+=2;return s}
function relatedRows(all,rec){return (all||[]).filter(a=>a?.slug&&a.slug!==rec.slug&&a.indexable!==false).map((a,i)=>({a,s:scoreRelated(a,rec),i})).sort((x,y)=>y.s-x.s||x.i-y.i).slice(0,6).map(x=>x.a)}
function relatedHtml(rec,rows){const isAE=rec.country==='AE',market=isAE?'الإمارات':'السعودية',marketPath=isAE?'uae':'saudi-arabia',cards=rows.map(a=>`<article class="nl-card"><small>${a.country==='AE'?'الإمارات':'السعودية'} · ${esc(a.intentLabel||a.intent||'دليل')}</small><h3><a href="/articles/${enc(a.slug)}">${esc(a.title||a.primaryKeyword||a.slug)}</a></h3><p>${esc((a.metaDescription||'').slice(0,150))}</p><a class="nl-read" href="/articles/${enc(a.slug)}">اقرأ المقال ←</a></article>`).join('');return `<section id="article-link-network" dir="rtl"><div class="nl-wrap"><div class="nl-head"><div><span>مقالات مرتبطة</span><h2>اقرأ أيضًا قبل الشراء</h2><p>روابط منتقاة حسب السوق والقسم وهدف البحث لتسهيل الانتقال بين الأدلة.</p></div><a href="/blog">كل المقالات</a></div><div class="nl-grid">${cards}</div><nav class="nl-spider" aria-label="روابط مهمة"><a href="/">الرئيسية</a><a href="/blog">المدونة</a><a href="/${marketPath}/noon-coupon-code">كود خصم نون ${market}</a><a href="/${marketPath}/noon-coupon-code-today">كود نون اليوم</a>${rec.landingPath?`<a href="${esc(rec.landingPath)}">صفحة القسم المرتبطة</a>`:''}</nav></div></section>`}
function ensureImageAlts(html,rec){let n=0;const base=String(rec.title||rec.primaryKeyword||'دليل كوبونات نون').replace(/\s+/g,' ').trim();return String(html).replace(/<img\b[^>]*>/gi,tag=>{let out=tag;if(!/\balt\s*=\s*["'][^"']+["']/i.test(out)){n++;out=out.replace(/<img\b/i,`<img alt="${esc(base)} - صورة توضيحية ${n}"`)}if(!/\bloading\s*=/i.test(out)&&n>1)out=out.replace(/<img\b/i,'<img loading="lazy"');if(!/\bdecoding\s*=/i.test(out))out=out.replace(/<img\b/i,'<img decoding="async"');return out})}
function mergeExternalRel(tag){const m=tag.match(/\brel\s*=\s*(["'])([^"']*)\1/i);const required=['noopener','external'];if(!m)return tag.replace(/>$/,` rel="${required.join(' ')}">`);const current=m[2].split(/\s+/).filter(Boolean),set=new Set(current.map(x=>x.toLowerCase()));for(const token of required)if(!set.has(token))current.push(token);return tag.replace(m[0],`rel=${m[1]}${current.join(' ')}${m[1]}`)}
function secureExternalLinks(html,origin){let host='';try{host=new URL(origin).host}catch{}return String(html).replace(/<a\b[^>]*href=(['"])(https?:\/\/[^'"\s>]+)\1[^>]*>/gi,(tag,q,href)=>{let external=false;try{external=new URL(href).host!==host}catch{}return external?mergeExternalRel(tag):tag})}
function networkCss(){return `<style id="article-link-network-css">#article-link-network{margin:34px 0 0;padding:32px 0;background:#f8fafc;border-top:1px solid #e5e7eb;font-family:Tahoma,Arial,sans-serif}.nl-wrap{width:min(1080px,92%);margin:auto}.nl-head{display:flex;justify-content:space-between;align-items:end;gap:16px}.nl-head span,.nl-read{color:#6d28d9;font-weight:900}.nl-head h2{margin:5px 0}.nl-head p,.nl-card p{color:#64748b;line-height:1.8}.nl-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:18px}.nl-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px}.nl-card h3{line-height:1.55}.nl-card a{text-decoration:none;color:#111827}.nl-spider{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.nl-spider a{background:#111827;color:#fff;text-decoration:none;border-radius:999px;padding:9px 12px;font-weight:800}@media(max-width:820px){.nl-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.nl-grid{grid-template-columns:1fr}.nl-head{display:block}}</style>`}
function conversionLayer(){const approved=JSON.stringify(APPROVED_COUPON_CODES);return `<style id="coupon-conversion-css">.coupon-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.coupon .copy-code{border:0;cursor:pointer;font:inherit}.coupon .shop-link{display:inline-block;border:1px solid #d1d5db;background:#fff;color:#111827;text-decoration:none;font-weight:800;padding:12px 15px;border-radius:12px}.coupon .copy-code[data-copied="1"]{background:#16a34a;color:#fff}</style><script id="coupon-conversion-js">(()=>{const approved=new Set(${approved});const fire=(name,data)=>{try{if(typeof window.gtag==='function')window.gtag('event',name,data);else{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...data})}}catch{}};const copy=async text=>{try{await navigator.clipboard.writeText(text);return true}catch{try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}};document.querySelectorAll('.coupon').forEach((box,index)=>{const code=(box.querySelector('.code')?.textContent||'').trim().toUpperCase();const shop=box.querySelector('a.cta');if(!approved.has(code)||!shop||box.querySelector('.copy-code'))return;const market=location.pathname.startsWith('/uae')?'AE':'SA';const wrap=document.createElement('div');wrap.className='coupon-actions';const btn=document.createElement('button');btn.type='button';btn.className='cta copy-code';btn.dataset.code=code;btn.dataset.market=market;btn.dataset.placement='commerce_coupon_box';btn.textContent='نسخ الكود';shop.classList.remove('cta');shop.classList.add('shop-link');shop.parentNode.replaceChild(wrap,shop);wrap.append(btn,shop);btn.addEventListener('click',async()=>{const ok=await copy(code);btn.dataset.copied=ok?'1':'0';btn.textContent=ok?'تم النسخ ✓':'انسخ '+code;fire('copy_code',{coupon_code:code,market,page_path:location.pathname,placement:btn.dataset.placement,copy_success:ok})});shop.addEventListener('click',()=>fire('shop_click',{coupon_code:code,market,page_path:location.pathname,placement:'commerce_coupon_box',destination:shop.href}));fire('coupon_view',{coupon_code:code,market,page_path:location.pathname,placement:'commerce_coupon_box',box_index:index})})})();</script>`}
function enhanceConversionHtml(html){let out=String(html).replace(/href=(['"])\/saudi\/noon-coupon-code([^'"\s>]*)\1/gi,(m,q,suffix)=>`href=${q}/saudi-arabia/noon-coupon-code${suffix}${q}`);if(out.includes('class="coupon"')&&!out.includes('id="coupon-conversion-js"'))out=out.replace(/<\/body>/i,conversionLayer()+'</body>');return out}
async function enhanceArticle(req,env,res){if(!res.ok||!(res.headers.get('content-type')||'').includes('text/html'))return res;const u=new URL(req.url),slug=decodeURIComponent(u.pathname.split('/').filter(Boolean).pop()||'');if(!slug)return res;const latest=await latestManifest(env);const all=(latest.articles||[]).filter(a=>a?.slug&&a.indexable!==false);let rec=all.find(a=>a.slug===slug)||{slug,country:'SA'};if(!rec.category&&!rec.categoryKey){try{const o=await env.CONTENT_FINAL?.head('articles/'+slug+'.html'),md=o?.customMetadata||{};rec={...rec,country:md.c||rec.country,category:md.cat||rec.category,categoryKey:md.cat||rec.categoryKey,brandKey:md.bk||rec.brandKey,modelKey:md.mk||rec.modelKey,landingPath:md.lp||rec.landingPath,title:md.t?decodeURIComponent(md.t):rec.title,primaryKeyword:md.kw?decodeURIComponent(md.kw):rec.primaryKeyword}}catch{}}
const related=relatedRows(all,rec);let html=await res.text();html=replaceUnapprovedCouponTokens(html,'OPS32');html=ensureImageAlts(html,rec);html=secureExternalLinks(html,env.SITE_ORIGIN||u.origin);if(!html.includes('id="article-link-network"'))html=html.replace(/<\/body>/i,relatedHtml(rec,related)+'</body>');if(!html.includes('id="article-link-network-css"'))html=html.replace(/<\/head>/i,networkCss()+'</head>');html=enhanceConversionHtml(html);const h=new Headers(res.headers);h.delete('content-length');h.set('x-article-network','v1');h.set('x-related-articles',String(related.length));h.set('x-alt-fallback','enabled');h.set('x-external-link-safety','merged-v2');h.set('x-related-manifest-cache','120s-isolate');h.set('x-coupon-whitelist','ops-v3');h.set('x-copy-code-primary','enabled');h.set('x-conversion-dispatch','single-v2');return new Response(html,{status:res.status,statusText:res.statusText,headers:h})}
async function enhancePage(res){if(!res.ok||!(res.headers.get('content-type')||'').includes('text/html'))return res;const original=await res.text(),html=enhanceConversionHtml(original);if(html===original)return new Response(original,{status:res.status,statusText:res.statusText,headers:res.headers});const h=new Headers(res.headers);h.delete('content-length');h.set('x-copy-code-primary','enabled');h.set('x-saudi-money-links','canonical');h.set('x-conversion-dispatch','single-v2');return new Response(html,{status:res.status,statusText:res.statusText,headers:h})}
export default{async fetch(req,env,ctx){let res=await app.fetch(req,env,ctx);const path=new URL(req.url).pathname;if(req.method==='GET'&&path.startsWith('/articles/'))res=await enhanceArticle(req,env,res);else if(req.method==='GET')res=await enhancePage(res);return res},async scheduled(event,env,ctx){if(app.scheduled)return app.scheduled(event,env,ctx)}};
export const ARTICLE_NETWORK_INFO={version:5,relatedArticles:6,altFallback:true,externalRelSafety:'merged-v2',relatedManifestCacheSeconds:120,marketMoneyLinks:true,couponWhitelist:true,copyCodePrimary:true,conversionDispatch:'single-v2',conversionEvents:['coupon_view','copy_code','shop_click']};
