import app from './router.js';
import {TRUST_PAGES} from './trust-content.js';
import {APPROVED_COUPON_CODES} from './approved-coupons.js';

const ORIGIN='https://noondealsnow.com';
const CODES=APPROVED_COUPON_CODES;
const ROUTES={
  '/editorial-policy':'editorial',
  '/coupon-verification':'verification',
  '/authors/editorial-team':'team',
  '/disclaimer':'disclaimer',
  '/terms':'terms'
};
const CORE_TRUST_LINKS=[['/about','من نحن'],['/contact','اتصل بنا'],['/privacy','الخصوصية']];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bodies={
  editorial:`<h2>الدقة قبل التسويق</h2><p>لا ننشر نسبة خصم أو حدًا أقصى أو أهلية كحقيقة إذا لم تكن الشروط موثقة. عندما تكون البيانات المتاحة هي الكود فقط، نعرضه للتجربة ونترك نتيجة السلة هي المرجع النهائي.</p><h2>فصل الأسواق</h2><p>السعودية والإمارات صفحتان مستقلتان لأن العملة والأهلية وشروط الحملات قد تختلف. مصر مخططة لكنها غير منشورة حاليًا.</p><h2>المراجعة</h2><p>أي تحديث تجاري يجب أن يراعي الدولة وتاريخ التحقق ومصدر المعلومة قبل تحويله إلى Claim ظاهر للمستخدم.</p>`,
  verification:`<h2>ما الذي يتم التحقق منه؟</h2><p>نفرّق بين وجود الكود وبين شروطه. الأكواد الحالية متاحة للنسخ والتجربة، لكن نسب الخصم والحدود والأهلية لا تُعرض كحقائق بدون بيانات موثقة.</p><h2>المرجع النهائي</h2><p>إجمالي السلة بعد إدخال الكود هو المرجع العملي النهائي. إذا لم يتغير السعر أو ظهرت رسالة عدم أهلية، راجع الدولة والحساب والمنتجات ثم جرّب كودًا آخر.</p><div class="note">لا نستخدم عبارة «مضمون 100%» للكوبون بدون دليل كافٍ على شروطه وحالته.</div>`,
  team:`<h2>مسؤولية تحريرية واضحة</h2><p>يُنشر المحتوى باسم فريق تحرير كوبونات نون كجهة تحريرية للموقع. لا نختلق أسماء خبراء أو تجارب شخصية لتحسين إشارات E‑E‑A‑T.</p><h2>الدور</h2><p>تنظيم الأكواد حسب السوق، مراجعة الادعاءات، تحسين تجربة الاستخدام، والحفاظ على فصل واضح بين المعلومة المؤكدة والإرشاد العام.</p><h2>معايير المراجعة</h2><ul><li>استخدام الأكواد الموجودة في القائمة المعتمدة فقط.</li><li>عدم تحويل نسبة خصم أو انتهاء أو أهلية إلى حقيقة بدون دليل موثوق.</li><li>فصل السعودية والإمارات وعدم نقل نتيجة سوق إلى الآخر كأنها مؤكدة.</li><li>إبقاء بوابة جودة المحتوى والتميّز ومنع التكرار قبل النشر.</li></ul><div class="note">راجع أيضًا <a href="/editorial-policy">السياسة التحريرية</a> و<a href="/coupon-verification">منهجية التحقق</a> و<a href="/research">صفحة البيانات والمنهجية</a>.</div>`,
  disclaimer:`<h2>موقع مستقل</h2><p>الموقع مستقل وليس الموقع الرسمي لـNoon ولا يمثل الشركة. تُستخدم أسماء العلامات لتحديد موضوع صفحات الكوبونات والتسوق.</p><h2>تغير العروض</h2><p>العروض والشروط والأهلية قد تتغير، لذلك يجب مراجعة السعر والشروط داخل متجر Noon قبل إتمام الشراء.</p>`,
  terms:`<h2>استخدام المعلومات</h2><p>المحتوى يساعد على اكتشاف الأكواد وفهم طريقة تجربتها. قرار الشراء والسعر النهائي يخضعان لمتجر Noon وشروطه.</p><h2>العلامات والروابط</h2><p>العلامات التجارية وحقوقها تعود لأصحابها، وقد تتغير صفحات المتاجر والعروض دون إشعار من هذا الموقع.</p><h2>التحديثات</h2><p>يجوز تحديث الصفحات والمنهجية عندما تتوفر بيانات أفضل أو تتغير البنية التقنية للموقع.</p>`
};
const css=`body{margin:0;background:#f7f7fb;color:#111827;font-family:Tahoma,Arial,sans-serif}.wrap{width:min(900px,92%);margin:40px auto}.back{color:#5b21b6;text-decoration:none;font-weight:800}.card{margin-top:18px;background:#fff;border:1px solid #e6e9ef;border-radius:24px;padding:28px;box-shadow:0 16px 50px rgba(17,24,39,.07);line-height:2}.card h1{font-size:42px;line-height:1.15;margin:10px 0}.card h2{margin-top:28px}.muted{color:#667085}.note{padding:15px;border-radius:15px;background:#fffbeb;border:1px solid #fde68a;color:#854d0e}.nav{display:flex;flex-wrap:wrap;gap:8px;margin-top:24px}.nav a{padding:8px 11px;border-radius:999px;background:#f5f3ff;color:#5b21b6;text-decoration:none;font-size:12px;font-weight:800}`;
const globalCss=`<style>.nc-all{padding:42px 0;background:#fff}.nc-wrap{width:min(1180px,92%);margin:auto}.nc-title{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-bottom:18px}.nc-title h2{font-size:30px;margin:0}.nc-title p{margin:7px 0 0;color:#667085;line-height:1.8}.nc-code-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.nc-code{display:block;border:1px solid #e6e9ef;background:linear-gradient(180deg,#fff,#faf8ff);border-radius:18px;padding:16px;text-align:center;box-shadow:0 10px 30px rgba(17,24,39,.06);text-decoration:none}.nc-code b{font:900 19px monospace;letter-spacing:1.5px;color:#5b21b6}.nc-code span{display:block;font-size:12px;color:#667085;margin-top:7px}.nc-trustbar{background:#0f172a;color:#cbd5e1;padding:18px 0;border-top:1px solid #26324a}.nc-trustbar .nc-wrap{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.nc-trustlinks{display:flex;flex-wrap:wrap;gap:10px}.nc-trustlinks a{color:#e9d5ff;text-decoration:none;font-size:12px;font-weight:800}@media(max-width:850px){.nc-code-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.nc-code-grid{grid-template-columns:1fr}}</style>`;
function page(path,key){
 const d=TRUST_PAGES[key],nav=[...Object.entries(ROUTES).map(([r,k])=>[r,TRUST_PAGES[k].title]),...CORE_TRUST_LINKS].map(([r,label])=>`<a href="${r}">${label}</a>`).join('');
 const pageType=key==='team'?'ProfilePage':'WebPage';
 const graph=[
  {'@type':'Organization','@id':ORIGIN+'/#organization',name:'Noon Deals Now',alternateName:'كوبونات نون',url:ORIGIN+'/'},
  {'@type':'WebSite','@id':ORIGIN+'/#website',name:'Noon Deals Now',alternateName:'كوبونات نون',url:ORIGIN+'/',inLanguage:['ar','en'],publisher:{'@id':ORIGIN+'/#organization'}},
  {'@type':pageType,'@id':ORIGIN+path+'#webpage',name:d.title,description:d.description,url:ORIGIN+path,inLanguage:'ar',isPartOf:{'@id':ORIGIN+'/#website'},publisher:{'@id':ORIGIN+'/#organization'},...(key==='team'?{mainEntity:{'@id':ORIGIN+path+'#team'}}:{})},
  {'@type':'BreadcrumbList','@id':ORIGIN+path+'#breadcrumb',itemListElement:[
   {'@type':'ListItem',position:1,name:'الرئيسية',item:ORIGIN+'/'},
   {'@type':'ListItem',position:2,name:d.title,item:ORIGIN+path}
  ]}
 ];
 if(key==='team')graph.push({'@type':'Organization','@id':ORIGIN+path+'#team',name:'Noon Deals Now Editorial Team',alternateName:'فريق تحرير كوبونات نون',url:ORIGIN+path,parentOrganization:{'@id':ORIGIN+'/#organization'},knowsAbout:['Coupon verification','Editorial quality','Noon Saudi Arabia','Noon UAE'],description:d.description});
 const schema=JSON.stringify({'@context':'https://schema.org','@graph':graph});
 return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.title)} | كوبونات نون</title><meta name="description" content="${esc(d.description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${ORIGIN+path}"><style>${css}</style><script type="application/ld+json" data-schema="${key==='team'?'editorial-team-profile':'trust-page'}">${schema}</script></head><body><main class="wrap"><a class="back" href="/">← الرئيسية</a><article class="card"><div class="muted">Trust & Editorial</div><h1>${esc(d.title)}</h1><p class="muted">${esc(d.description)}</p>${bodies[key]}<div class="nav">${nav}</div></article></main></body></html>`
}
function allCodes(){return `${globalCss}<section class="nc-all" id="all-current-codes"><div class="nc-wrap"><div class="nc-title"><div><h2>الأكواد الحالية — كلها أمامك</h2><p>اضغط على أي كود لفتح صفحته، ثم جرّبه في السوق المناسب وتحقق من الخصم داخل السلة.</p></div><a href="/coupons">عرض 20 بطاقة السعودية والإمارات ←</a></div><div class="nc-code-grid">${CODES.map(c=>`<a class="nc-code" href="/coupon/${c.toLowerCase()}"><b>${c}</b><span>فتح صفحة الكود</span></a>`).join('')}</div></div></section>`}
function discoveryHub(){return `<section id="discovery-hub" style="padding:38px 0;background:#f7f7fb"><div class="nc-wrap"><div class="nc-title"><div><h2>ابدأ من الصفحات الأكثر فائدة</h2><p>روابط مباشرة للأسواق وصفحات الشراء والأدلة التي تساعدك على الوصول للكود المناسب بسرعة.</p></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px"><a class="nc-code" href="/saudi"><b style="font-family:inherit;letter-spacing:0">🇸🇦 نون السعودية</b><span>الأكواد والصفحات الخاصة بالسعودية</span></a><a class="nc-code" href="/uae"><b style="font-family:inherit;letter-spacing:0">🇦🇪 نون الإمارات</b><span>الأكواد والصفحات الخاصة بالإمارات</span></a><a class="nc-code" href="/coupon/best-noon-coupon-today"><b style="font-family:inherit;letter-spacing:0">أفضل كود نون اليوم</b><span>طريقة اختيار الكود الأنسب للسلة</span></a><a class="nc-code" href="/coupon/noon-new-subscribers-2026"><b style="font-family:inherit;letter-spacing:0">الطلب الأول</b><span>دليل العملاء الجدد والأهلية</span></a><a class="nc-code" href="/coupon/noon-mobiles-coupon-2026"><b style="font-family:inherit;letter-spacing:0">الموبايلات</b><span>صفحة شراء للموبايلات والإلكترونيات</span></a><a class="nc-code" href="/coupon/noon-fashion-clothing-coupon"><b style="font-family:inherit;letter-spacing:0">الأزياء</b><span>كوبونات نون للأزياء والملابس</span></a><a class="nc-code" href="/coupon/noon-beauty-perfumes-coupon-2026"><b style="font-family:inherit;letter-spacing:0">الجمال والعطور</b><span>صفحة موجهة للجمال والعطور</span></a><a class="nc-code" href="/guide/how-to-use-noon-coupon"><b style="font-family:inherit;letter-spacing:0">طريقة استخدام الكود</b><span>خطوات النسخ والتجربة قبل الدفع</span></a><a class="nc-code" href="/guide/coupon-not-working"><b style="font-family:inherit;letter-spacing:0">الكود لا يعمل؟</b><span>تشخيص أسباب رفض الكوبون</span></a><a class="nc-code" href="/en/saudi"><b style="font-family:inherit;letter-spacing:0">English · Saudi</b><span>Saudi English buying guides</span></a><a class="nc-code" href="/en/uae"><b style="font-family:inherit;letter-spacing:0">English · UAE</b><span>UAE English buying guides</span></a></div></div></section>`}
function trustBar(){return `${globalCss}<section class="nc-trustbar"><div class="nc-wrap"><div><b>شفافية المحتوى</b><div style="font-size:12px;margin-top:4px">نميز بين الكود المتاح للتجربة وبين شروط الخصم الموثقة.</div></div><div class="nc-trustlinks"><a href="/coupon-verification">منهجية التحقق</a><a href="/editorial-policy">السياسة التحريرية</a><a href="/authors/editorial-team">فريق التحرير</a><a href="/disclaimer">الاستقلالية</a><a href="/terms">الشروط</a><a href="/about">من نحن</a><a href="/contact">اتصل بنا</a><a href="/privacy">الخصوصية</a></div></div></section>`}
async function enhance(request,env,ctx,path){const res=await app.fetch(request,env,ctx);if(!res.headers.get('content-type')?.includes('text/html'))return res;let html=await res.text();if(path!=='/'&&!html.includes('nc-trustbar'))html=html.replace('</body>',trustBar()+'</body>');const headers=new Headers(res.headers);headers.delete('content-length');headers.set('content-type','text/html; charset=utf-8');headers.set('cache-control','public, max-age=0, s-maxage=300');return new Response(html,{status:res.status,headers})}
async function sitemap(request,env,ctx){const res=await app.fetch(request,env,ctx);let xml=await res.text();const extra=Object.keys(ROUTES).filter(r=>!xml.includes(ORIGIN+r)).map(r=>`<url><loc>${ORIGIN+r}</loc><changefreq>monthly</changefreq><priority>0.5</priority></url>`).join('');xml=xml.replace('</urlset>',extra+'</urlset>');return new Response(xml,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=300'}})}
export default{async fetch(request,env,ctx){const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';if(ROUTES[path])return new Response(page(path,ROUTES[path]),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=0, s-maxage=300'}});if(path==='/sitemap.xml')return sitemap(request,env,ctx);if(path.startsWith('/api/')||path==='/admin')return app.fetch(request,env,ctx);return enhance(request,env,ctx,path)},async scheduled(event,env,ctx){if(app.scheduled)return app.scheduled(event,env,ctx)}};
