import app from './router.js';
import {TRUST_PAGES} from './trust-content.js';

const ORIGIN='https://nooncoupons.ramychatgptgcoupons.workers.dev';
const ROUTES={
  '/editorial-policy':'editorial',
  '/coupon-verification':'verification',
  '/authors/editorial-team':'team',
  '/disclaimer':'disclaimer'
};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bodies={
  editorial:`<h2>الدقة قبل التسويق</h2><p>لا ننشر نسبة خصم أو حدًا أقصى أو أهلية كحقيقة إذا لم تكن الشروط موثقة. عندما تكون البيانات المتاحة هي الكود فقط، نعرضه للتجربة ونترك نتيجة السلة هي المرجع النهائي.</p><h2>فصل الأسواق</h2><p>السعودية والإمارات صفحتان مستقلتان لأن العملة والأهلية وشروط الحملات قد تختلف. مصر مخططة لكنها غير منشورة حاليًا.</p><h2>المراجعة</h2><p>أي تحديث تجاري يجب أن يراعي الدولة وتاريخ التحقق ومصدر المعلومة قبل تحويله إلى Claim ظاهر للمستخدم.</p>`,
  verification:`<h2>ما الذي يتم التحقق منه؟</h2><p>نفرّق بين وجود الكود وبين شروطه. الأكواد الحالية متاحة للنسخ والتجربة، لكن نسب الخصم والحدود والأهلية لا تُعرض كحقائق بدون بيانات موثقة.</p><h2>المرجع النهائي</h2><p>إجمالي السلة بعد إدخال الكود هو المرجع العملي النهائي. إذا لم يتغير السعر أو ظهرت رسالة عدم أهلية، راجع الدولة والحساب والمنتجات ثم جرّب كودًا آخر.</p><div class="note">لا نستخدم عبارة «مضمون 100%» للكوبون بدون دليل كافٍ على شروطه وحالته.</div>`,
  team:`<h2>مسؤولية تحريرية واضحة</h2><p>يُنشر المحتوى باسم فريق تحرير كوبونات نون كجهة تحريرية للموقع. لا نختلق أسماء خبراء أو تجارب شخصية لتحسين إشارات E‑E‑A‑T.</p><h2>الدور</h2><p>تنظيم الأكواد حسب السوق، مراجعة الادعاءات، تحسين تجربة الاستخدام، والحفاظ على فصل واضح بين المعلومة المؤكدة والإرشاد العام.</p>`,
  disclaimer:`<h2>موقع مستقل</h2><p>الموقع مستقل وليس الموقع الرسمي لـNoon ولا يمثل الشركة. تُستخدم أسماء العلامات لتحديد موضوع صفحات الكوبونات والتسوق.</p><h2>تغير العروض</h2><p>العروض والشروط والأهلية قد تتغير، لذلك يجب مراجعة السعر والشروط داخل متجر Noon قبل إتمام الشراء.</p>`
};
const css=`body{margin:0;background:#f7f7fb;color:#111827;font-family:Tahoma,Arial,sans-serif}.wrap{width:min(900px,92%);margin:40px auto}.back{color:#5b21b6;text-decoration:none;font-weight:800}.card{margin-top:18px;background:#fff;border:1px solid #e6e9ef;border-radius:24px;padding:28px;box-shadow:0 16px 50px rgba(17,24,39,.07);line-height:2}.card h1{font-size:42px;line-height:1.15;margin:10px 0}.card h2{margin-top:28px}.muted{color:#667085}.note{padding:15px;border-radius:15px;background:#fffbeb;border:1px solid #fde68a;color:#854d0e}.nav{display:flex;flex-wrap:wrap;gap:8px;margin-top:24px}.nav a{padding:8px 11px;border-radius:999px;background:#f5f3ff;color:#5b21b6;text-decoration:none;font-size:12px;font-weight:800}`;
function page(path,key){const d=TRUST_PAGES[key];const nav=Object.entries(ROUTES).map(([r,k])=>`<a href="${r}">${TRUST_PAGES[k].title}</a>`).join('');const schema=JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:d.title,description:d.description,url:ORIGIN+path});return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.title)} | كوبونات نون</title><meta name="description" content="${esc(d.description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${ORIGIN+path}"><style>${css}</style><script type="application/ld+json">${schema}</script></head><body><main class="wrap"><a class="back" href="/">← الرئيسية</a><article class="card"><div class="muted">Trust & Editorial</div><h1>${esc(d.title)}</h1><p class="muted">${esc(d.description)}</p>${bodies[key]}<div class="nav">${nav}</div></article></main></body></html>`}
async function sitemap(request,env,ctx){const res=await app.fetch(request,env,ctx);let xml=await res.text();const extra=Object.keys(ROUTES).filter(r=>!xml.includes(ORIGIN+r)).map(r=>`<url><loc>${ORIGIN+r}</loc><changefreq>monthly</changefreq><priority>0.5</priority></url>`).join('');xml=xml.replace('</urlset>',extra+'</urlset>');return new Response(xml,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=300'}})}
export default{async fetch(request,env,ctx){const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';if(ROUTES[path])return new Response(page(path,ROUTES[path]),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=0, s-maxage=300'}});if(path==='/sitemap.xml')return sitemap(request,env,ctx);return app.fetch(request,env,ctx)},async scheduled(event,env,ctx){if(app.scheduled)return app.scheduled(event,env,ctx)}};
