import {matchesArabicSearch,arabicSearchTokens,ARABIC_SEARCH_INFO} from './arabic-search.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=s=>encodeURI(String(s||''));
const safe=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const HUBS={
'/topics/buying-guides':{title:'أدلة شراء نون',description:'أدلة عملية لاختيار المنتجات على نون ومراجعة القرار قبل الدفع.',intents:['decision','smartbuy','budget','checklist']},
'/topics/coupon-help':{title:'حل مشاكل كوبونات نون',description:'استخدام الكوبون وأسباب رفض الكود وشروط الأهلية.',intents:['trouble','eligibility','howto','question','timing']},
'/topics/price-and-cart':{title:'السعر والسلة على نون',description:'مقارنة الأسعار وحساب الإجمالي والتوفير قبل الدفع.',intents:['compare','finalprice','value','cart','multi']},
'/topics/returns-and-warranty':{title:'الإرجاع والضمان والبائع',description:'مراجعة البائع والإرجاع والضمان قبل الشراء.',intents:['returns','warranty','seller']},
'/topics/saudi':{title:'أدلة نون السعودية',description:'أحدث الأدلة المخصصة لسوق نون السعودية.',country:'SA'},
'/topics/uae':{title:'أدلة نون الإمارات',description:'أحدث الأدلة المخصصة لسوق نون الإمارات.',country:'AE'}
};
const MARKETS={saudi:{country:'SA',label:'السعودية',name:'نون السعودية',noon:'https://www.noon.com/saudi-ar/'},uae:{country:'AE',label:'الإمارات',name:'نون الإمارات',noon:'https://www.noon.com/uae-ar/'}};
const CODES=['NOV170','NOV188','NOV174','NOV157','NOV177','NOV186','NOV163','NOV153','NOV195','NOV161'];
const CATS={
  electronics:{label:'الإلكترونيات',desc:'اختيار الإلكترونيات مع مراجعة النسخة والبائع والضمان والسعر النهائي.',terms:['التلفزيونات','الكاميرات','الشاشات','الراوترات','التخزين الخارجي','التابلت','الساعات الذكية','الأجهزة القابلة للارتداء']},
  mobiles:{label:'الجوالات',desc:'الجوالات حسب السعة والنسخة الإقليمية والبائع والضمان والكوبون.',terms:['الجوالات'],brands:true},
  computers:{label:'اللابتوبات والكمبيوتر',desc:'اللابتوبات والكمبيوتر حسب المعالج والذاكرة والتخزين والضمان.',terms:['اللابتوبات','إكسسوارات الكمبيوتر','المكتب المنزلي','الطابعات']},
  gaming:{label:'الألعاب الإلكترونية',desc:'أجهزة وإكسسوارات الألعاب مع مراجعة التوافق والضمان.',terms:['أجهزة الألعاب','إكسسوارات الألعاب']},
  audio:{label:'السماعات والصوتيات',desc:'الصوتيات حسب الاتصال والبطارية والراحة والتوافق.',terms:['السماعات','الأجهزة الصوتية']},
  'home-kitchen':{label:'البيت والمطبخ',desc:'البيت والمطبخ حسب المقاس والخامة والسعة وسهولة الاستخدام.',terms:['المطبخ','منتجات القهوة','أدوات الطبخ','الأثاث','الديكور','أدوات التنظيف','المفروشات','الإضاءة','تنظيم المنزل']},
  appliances:{label:'الأجهزة المنزلية',desc:'الأجهزة المنزلية حسب السعة والأبعاد والتوافق والضمان.',terms:['الأجهزة المنزلية']},
  beauty:{label:'الجمال والعناية',desc:'الجمال والعناية مع مراجعة الحجم والمكونات المعلنة والبائع.',terms:['العطور','مستحضرات التجميل','العناية بالبشرة','العناية بالشعر','العناية الشخصية']},
  'women-fashion':{label:'أزياء النساء',desc:'أزياء النساء مع مراجعة المقاس والخامة وسياسة الإرجاع.',terms:['الأزياء النسائية','الأحذية','الحقائب']},
  'men-fashion':{label:'أزياء الرجال',desc:'أزياء الرجال مع مراجعة المقاس والخامة وسياسة الإرجاع.',terms:['الأزياء الرجالية','الأحذية','الحقائب']},
  'baby-kids':{label:'البيبي والأطفال',desc:'البيبي والأطفال حسب العمر والمقاس وطريقة الاستخدام.',terms:['مستلزمات المواليد','ألعاب الأطفال','الألعاب التعليمية']},
  sports:{label:'الرياضة واللياقة',desc:'الرياضة واللياقة حسب المقاس والوزن والخامة.',terms:['الرياضة واللياقة','معدات التخييم','الدراجات']},
  automotive:{label:'السيارات',desc:'إكسسوارات السيارات مع مراجعة التوافق وطريقة التركيب.',terms:['إكسسوارات السيارات']},
  grocery:{label:'البقالة',desc:'البقالة مع مراجعة حجم العبوة وسعر الوحدة والتخزين.',terms:['البقالة']},
  travel:{label:'السفر',desc:'مستلزمات السفر حسب الأبعاد والوزن والسعة وسهولة الحركة.',terms:['شنط السفر']}
};
const BRANDS={
  apple:{label:'Apple iPhone',short:'آيفون',models:['iPhone','iPhone Pro','iPhone Plus / Pro Max']},
  samsung:{label:'Samsung Galaxy',short:'سامسونج',models:['Galaxy S','Galaxy A','Galaxy Z']},
  xiaomi:{label:'Xiaomi',short:'شاومي',models:['Xiaomi','Redmi Note','POCO']},
  oppo:{label:'OPPO',short:'أوبو',models:['Reno','Find','A Series']},
  honor:{label:'HONOR',short:'هونر',models:['Magic','X Series','Number Series']},
  huawei:{label:'Huawei',short:'هواوي',models:['Mate','Pura','nova']},
  motorola:{label:'Motorola',short:'موتورولا',models:['Edge','Moto G','Razr']},
  vivo:{label:'vivo',short:'فيفو',models:['X Series','V Series','Y Series']}
};
const COMPS={
  'iphone-vs-galaxy':{title:'آيفون أم Samsung Galaxy؟',a:'apple',b:'samsung'},
  'samsung-vs-xiaomi':{title:'Samsung أم Xiaomi؟',a:'samsung',b:'xiaomi'},
  'oppo-vs-honor':{title:'OPPO أم HONOR؟',a:'oppo',b:'honor'},
  'xiaomi-vs-honor':{title:'Xiaomi أم HONOR؟',a:'xiaomi',b:'honor'},
  'galaxy-s-vs-a':{title:'Galaxy S أم Galaxy A؟',a:'samsung',b:'samsung'}
};
const CATMAP={};for(const [k,c] of Object.entries(CATS))for(const t of c.terms)if(!CATMAP[t])CATMAP[t]=k;
const PAGE_CSS=`body{margin:0;font-family:Tahoma,Arial,sans-serif;background:#f8fafc;color:#111827}.w{width:min(1180px,92%);margin:auto}.hero{background:linear-gradient(135deg,#111827,#312e81);color:#fff;padding:42px 0}.hero p,.muted{color:#667085;line-height:1.9}.hero p{color:#e5e7eb}.crumbs,.chips,.hub-tabs{display:flex;gap:8px;flex-wrap:wrap}.crumbs a{color:#ddd6fe}.chips a,.hub-tabs a{background:#fff;border:1px solid #e5e7eb;border-radius:999px;padding:9px 12px;text-decoration:none;color:#111827;font-weight:800}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card,.coupon{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:18px}.card h2{font-size:20px}.card a{color:#111827;text-decoration:none}.read{color:#6d28d9!important;font-weight:900}.section{padding:28px 0}.section h2{font-size:26px;margin:0 0 10px}.catgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.catgrid a{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:17px;text-decoration:none;color:#111827}.catgrid strong{display:block;font-size:18px;margin-bottom:6px}.catgrid small{color:#667085;line-height:1.7}.coupon{display:grid;grid-template-columns:1fr auto;gap:15px;align-items:center;margin:22px 0;background:#fffbeb;border-color:#fde68a}.code{background:#111827;color:#fff;border-radius:10px;padding:7px 12px;font-weight:900;letter-spacing:1px}.cta{display:inline-block;background:#facc15;color:#111827;text-decoration:none;font-weight:900;padding:12px 15px;border-radius:12px}.check{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.check div{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:14px;line-height:1.8}.compare{width:100%;border-collapse:collapse;background:#fff}.compare td,.compare th{border:1px solid #e5e7eb;padding:12px;text-align:right}.spider{background:#111827;color:#fff;padding:26px 0}.spider a{background:#fff;color:#111827;text-decoration:none;border-radius:999px;padding:9px 12px;font-weight:800}.searchbox{display:flex;gap:8px;margin:16px 0}.searchbox input{flex:1;padding:12px;border:1px solid #d1d5db;border-radius:12px}.searchbox button{border:0;background:#6d28d9;color:#fff;padding:12px 18px;border-radius:12px;font-weight:900}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.catgrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.grid,.catgrid,.check,.coupon{grid-template-columns:1fr}}`;
async function latest(env){try{const o=await env.CONTENT_FINAL?.get('bulk/latest.json');return o?await o.json():{articles:[]}}catch{return {articles:[]}}}
const match=(h,a)=>a?.slug&&a.indexable!==false&&(!h.country||a.country===h.country)&&(!h.intents||h.intents.includes(a.intent));
const nav=()=>`<nav class="hub-tabs"><a href="/topics/buying-guides">أدلة الشراء</a><a href="/topics/coupon-help">مشاكل الكوبونات</a><a href="/topics/price-and-cart">السعر والسلة</a><a href="/topics/returns-and-warranty">الإرجاع والضمان</a><a href="/topics/saudi">السعودية</a><a href="/topics/uae">الإمارات</a></nav>`;
function card(a){return `<article class="card"><small>${a.country==='AE'?'الإمارات':'السعودية'} · ${esc(a.intentLabel||a.intent||'دليل')}</small><h2><a href="/articles/${enc(a.slug)}">${esc(a.title||a.primaryKeyword||a.slug)}</a></h2><p class="muted">${esc((a.metaDescription||'').slice(0,170))}</p><a class="read" href="/articles/${enc(a.slug)}">اقرأ الدليل ←</a></article>`}
function searchForm(v=''){return `<form class="searchbox" data-topic-search><input name="q" value="${esc(v)}" minlength="2" maxlength="60" required autocomplete="off" placeholder="ابحث عن منتج أو مشكلة كوبون أو دليل شراء"><button type="submit">بحث</button></form><script>(()=>{for(const f of document.querySelectorAll('[data-topic-search]'))f.addEventListener('submit',e=>{e.preventDefault();const q=(new FormData(f).get('q')||'').toString().trim().slice(0,60);if(q.length>1)location.href='/topics/search/'+encodeURIComponent(q)})})()</script>`}
function readSearch(path){if(path==='/topics/search')return '';if(!path.startsWith('/topics/search/'))return null;try{return decodeURIComponent(path.slice('/topics/search/'.length)).trim().slice(0,60)}catch{return ''}}
function searchable(a){return [a?.title,a?.primaryKeyword,a?.category,a?.intentLabel,a?.metaDescription,a?.coupon].filter(Boolean).join(' ')}
function marketPath(country){return country==='AE'?'uae':'saudi'}
function catForArticle(a={}){return CATMAP[a.category]||'electronics'}
function rowsFor(all,m,k){const c=CATS[k],mk=MARKETS[m];return all.filter(a=>a?.slug&&a.indexable!==false&&a.country===mk.country&&c.terms.includes(a.category)).slice(0,24)}
function codeFor(s){let n=0;for(const c of String(s||''))n=(n*31+c.charCodeAt(0))>>>0;return CODES[n%CODES.length]}
function crumbs(m,label=''){return `<div class="crumbs"><a href="/">الرئيسية</a><span>←</span><a href="/${m}/categories">أقسام ${MARKETS[m].name}</a>${label?`<span>←</span><span>${esc(label)}</span>`:''}</div>`}
function coupon(m,key,label){const mk=MARKETS[m],code=codeFor(m+key);return `<aside class="coupon"><div><small>كود من قائمة الموقع للتجربة</small><h2>جرّب <span class="code">${code}</span> عند شراء ${esc(label)}</h2><p class="muted">الأهلية وقيمة التوفير تتغير حسب الحساب والمنتج؛ راجع سلة نون قبل الدفع.</p></div><a class="cta" href="${mk.noon}" rel="noopener external sponsored">فتح ${mk.name}</a></aside>`}
function catCards(m){return `<div class="catgrid">${Object.entries(CATS).map(([k,c])=>`<a href="/${m}/category/${k}"><strong>${esc(c.label)}</strong><small>${esc(c.desc)}</small></a>`).join('')}</div>`}
function brandCards(m){return `<div class="catgrid">${Object.entries(BRANDS).map(([k,b])=>`<a href="/${m}/brand/${k}"><strong>${esc(b.label)}</strong><small>${esc(b.models.join(' · '))}</small></a>`).join('')}</div>`}
function spider(m,k=''){const ks=['mobiles','electronics','computers','home-kitchen','beauty','women-fashion','sports','automotive'];return `<section class="spider"><div class="w"><h2>تابع داخل شبكة الموقع</h2><div class="chips"><a href="/">الرئيسية</a><a href="/${m}/categories">كل الأقسام</a>${ks.filter(x=>x!==k).map(x=>`<a href="/${m}/category/${x}">${esc(CATS[x].label)}</a>`).join('')}<a href="/blog">المقالات</a></div></div></section>`}
function head(origin,path,title,desc,rows=[]){const graph={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',url:origin+path,name:title,description:desc,inLanguage:'ar',mainEntity:{'@type':'ItemList',itemListElement:rows.map((a,i)=>({'@type':'ListItem',position:i+1,url:origin+'/articles/'+enc(a.slug),name:a.title||a.slug}))}},{'@type':'BreadcrumbList',itemListElement:path.split('/').filter(Boolean).map((x,i,arr)=>({'@type':'ListItem',position:i+1,name:i===arr.length-1?title:x,item:origin+'/'+arr.slice(0,i+1).join('/')}))}]};return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | كوبونات نون</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(origin+path)}"><script type="application/ld+json">${safe(graph)}</script><style>${PAGE_CSS}</style>`}
async function searchLanding(path,origin,env){const query=readSearch(path);if(query===null)return null;const tokens=arabicSearchTokens(query),data=await latest(env),all=(data.articles||[]).filter(a=>a?.slug&&a.indexable!==false),rows=tokens.length?all.filter(a=>matchesArabicSearch(searchable(a),query)).slice(0,60):[],title=query?`نتائج البحث عن: ${query}`:'البحث في أدلة نون',html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | كوبونات نون</title><meta name="description" content="ابحث داخل أحدث أدلة نون السعودية والإمارات."><meta name="robots" content="noindex,follow"><link rel="canonical" href="${esc(origin+'/topics/search')}"><style>${PAGE_CSS}</style></head><body><header class="hero"><div class="w"><h1>${esc(title)}</h1><p>بحث عربي مرن داخل أحدث الأدلة التي اجتازت بوابة الجودة.</p></div></header><main class="w">${searchForm(query)}${nav()}<section class="grid">${rows.map(card).join('')}</section></main></body></html>`;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=30,s-maxage=60','x-robots-tag':'noindex, follow','x-topic-search':'v2','x-arabic-search':String(ARABIC_SEARCH_INFO.version)}})}
async function directory(m,origin,env){const mk=MARKETS[m];if(!mk)return null;const all=(await latest(env)).articles||[],rows=all.filter(a=>a?.slug&&a.indexable!==false&&a.country===mk.country).slice(0,12),path=`/${m}/categories`,title=`أقسام ${mk.name}`,desc=`تصفح الجوالات والإلكترونيات والبيت والجمال والأزياء والرياضة وباقي أقسام ${mk.name} داخل شبكة روابط منظمة.`;return new Response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${crumbs(m)}<h1>${title}</h1><p>${desc}</p></div></header><main class="w"><section class="section"><h2>كل الأقسام</h2>${catCards(m)}</section>${coupon(m,'all','أي قسم')}<section class="section"><h2>أحدث أدلة ${mk.label}</h2><div class="grid">${rows.map(card).join('')}</div></section></main>${spider(m)}</body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=90,s-maxage=300','x-commerce-hub':'market-v1'}})}
async function categoryPage(m,k,origin,env){const mk=MARKETS[m],c=CATS[k];if(!mk||!c)return null;const all=(await latest(env)).articles||[],rows=rowsFor(all,m,k),path=`/${m}/category/${k}`,title=`${c.label} على ${mk.name}`,desc=`${c.desc} الصفحة تربط الكوبون وأدلة الشراء والمقالات والصفحة الرئيسية في مسار واحد.`;return new Response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${crumbs(m,c.label)}<h1>${title}</h1><p>${desc}</p><div class="chips"><a href="/${m}/categories">كل الأقسام</a><a href="/topics/buying-guides">أدلة الشراء</a><a href="/topics/coupon-help">مشاكل الكوبون</a></div></div></header><main class="w">${coupon(m,k,c.label)}<section class="section"><h2>قبل الشراء</h2><div class="check"><div>حدد احتياجك ثم قارن المنتج نفسه لا اسم القسم فقط.</div><div>راجع البائع والنسخة أو المقاس والسعة المناسبة.</div><div>ثبت السلة ثم اختبر الكود وراجع الإجمالي النهائي.</div><div>راجع الشحن والإرجاع والضمان قبل الدفع.</div></div></section>${c.brands?`<section class="section"><h2>براندات الجوالات</h2>${brandCards(m)}</section>`:''}<section class="section"><h2>مقالات ${c.label}</h2><div class="grid">${rows.map(card).join('')||'<article class="card"><h2>المحتوى المتخصص قيد التوسع</h2><p class="muted">ستظهر المقالات هنا تلقائيًا عندما تجتاز بوابة الجودة.</p></article>'}</div></section><section class="section"><h2>أقسام أخرى</h2>${catCards(m)}</section></main>${spider(m,k)}</body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=90,s-maxage=300','x-commerce-hub':'category-v1','x-commerce-category':k}})}
async function brandPage(m,k,origin,env){const mk=MARKETS[m],b=BRANDS[k];if(!mk||!b)return null;const all=(await latest(env)).articles||[],specific=all.filter(a=>a?.slug&&a.indexable!==false&&a.country===mk.country&&searchable(a).toLowerCase().includes(b.short.toLowerCase())),rows=(specific.length?specific:rowsFor(all,m,'mobiles')).slice(0,18),path=`/${m}/brand/${k}`,title=`${b.label} على ${mk.name}`,desc=`بوابة ${b.label}: عائلات الأجهزة والمقارنات والكوبون وأدلة قرار الشراء على ${mk.name}.`;const models=b.models.map(x=>`<article class="card"><small>عائلة أجهزة</small><h2>${esc(x)}</h2><p class="muted">قارن السعة والنسخة والبائع والضمان والسعر النهائي داخل نون بدل الاعتماد على اسم السلسلة فقط.</p></article>`).join('');const compares=Object.entries(COMPS).filter(([,x])=>x.a===k||x.b===k).map(([ck,x])=>`<article class="card"><h2><a href="/${m}/compare/${ck}">${esc(x.title)}</a></h2><a class="read" href="/${m}/compare/${ck}">افتح المقارنة ←</a></article>`).join('');return new Response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${crumbs(m,b.label)}<h1>${title}</h1><p>${desc}</p><div class="chips"><a href="/${m}/category/mobiles">الجوالات</a><a href="/${m}/categories">كل الأقسام</a></div></div></header><main class="w">${coupon(m,'brand-'+k,b.label)}<section class="section"><h2>عائلات ${b.label}</h2><div class="grid">${models}</div></section><section class="section"><h2>مقارنات مرتبطة</h2><div class="grid">${compares}</div></section><section class="section"><h2>${specific.length?'مقالات البراند':'أدلة جوالات مرتبطة'}</h2><div class="grid">${rows.map(card).join('')}</div></section><section class="section"><h2>براندات أخرى</h2>${brandCards(m)}</section></main>${spider(m,'mobiles')}</body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=90,s-maxage=300','x-commerce-hub':'brand-v1','x-commerce-brand':k}})}
async function comparePage(m,k,origin,env){const mk=MARKETS[m],c=COMPS[k];if(!mk||!c)return null;const a=BRANDS[c.a],b=BRANDS[c.b],all=(await latest(env)).articles||[],rows=rowsFor(all,m,'mobiles').slice(0,12),path=`/${m}/compare/${k}`,title=`${c.title} — ${mk.label}`,desc=`مقارنة قرار شراء بين ${a.label} و${b.label} بدون تثبيت سعر أو مواصفة متغيرة.`;return new Response(`<!doctype html><html lang="ar" dir="rtl"><head>${head(origin,path,title,desc,rows)}</head><body><header class="hero"><div class="w">${crumbs(m,'مقارنة جوالات')}<h1>${title}</h1><p>${desc}</p><div class="chips"><a href="/${m}/brand/${c.a}">${a.label}</a><a href="/${m}/brand/${c.b}">${b.label}</a><a href="/${m}/category/mobiles">كل الجوالات</a></div></div></header><main class="w">${coupon(m,'compare-'+k,'الجوالات')}<section class="section"><h2>إطار المقارنة</h2><table class="compare"><tr><th>النقطة</th><th>${a.label}</th><th>${b.label}</th></tr><tr><td>الاستخدام</td><td>حدد الكاميرا أو الألعاب أو العمل أو الاستخدام اليومي.</td><td>قارن نفس الاستخدام لا اسم البراند فقط.</td></tr><tr><td>السعة والنسخة</td><td>ثبت السعة والنسخة قبل السعر.</td><td>لا تقارن سعرين لنسختين مختلفتين.</td></tr><tr><td>البائع والضمان</td><td>راجع البائع وحالة المنتج.</td><td>راجع الإرجاع والضمان بنفس الاهتمام.</td></tr><tr><td>الكوبون</td><td>اختبره بعد تثبيت السلة.</td><td>قارن الإجمالي النهائي بعد الشحن.</td></tr></table></section><section class="section"><h2>مقالات جوالات مرتبطة</h2><div class="grid">${rows.map(card).join('')}</div></section></main>${spider(m,'mobiles')}</body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=90,s-maxage=300','x-commerce-hub':'comparison-v1'}})}
async function commerce(path,origin,env){let x=path.match(/^\/(saudi|uae)\/categories$/);if(x)return directory(x[1],origin,env);x=path.match(/^\/(saudi|uae)\/category\/([a-z0-9-]+)$/);if(x)return categoryPage(x[1],x[2],origin,env);x=path.match(/^\/(saudi|uae)\/brand\/([a-z0-9-]+)$/);if(x)return brandPage(x[1],x[2],origin,env);x=path.match(/^\/(saudi|uae)\/compare\/([a-z0-9-]+)$/);if(x)return comparePage(x[1],x[2],origin,env);return null}
export function topicHubForArticle(a={}){if(['coupon','howto','trouble','question','eligibility','timing'].includes(a.intent))return {path:'/topics/coupon-help',...HUBS['/topics/coupon-help']};for(const [path,h] of Object.entries(HUBS)){if(h.intents?.includes(a.intent))return {path,...h}}const path=a.country==='AE'?'/topics/uae':'/topics/saudi';return {path,...HUBS[path]}}
export function articleTopicPathHtml(a={}){const h=topicHubForArticle(a),m=marketPath(a.country),k=catForArticle(a),c=CATS[k],market=a.country==='AE'?'نون الإمارات':'نون السعودية';return `<section id="article-topic-path" aria-label="مسار هذا الدليل"><div class="article-topic-path-inner"><p class="article-topic-kicker">تابع نفس الموضوع والقسم</p><h2>${esc(h.title)}</h2><p>${esc(h.description)}</p><div class="article-topic-actions"><a href="${h.path}">نفس الموضوع</a><a href="/${m}/category/${k}">${esc(c.label)}</a><a href="/${m}/categories">أقسام ${market}</a><a href="/blog">المقالات</a><a href="/">الرئيسية</a></div></div></section>`}
export async function topicLanding(path,origin,env){const search=await searchLanding(path,origin,env);if(search)return search;const cp=await commerce(path,origin,env);if(cp)return cp;const h=HUBS[path];if(!h)return null;const data=await latest(env),rows=(data.articles||[]).filter(a=>match(h,a)).slice(0,24),canonical=origin+path;const schema={'@context':'https://schema.org','@type':'CollectionPage',name:h.title,url:canonical,description:h.description,mainEntity:{'@type':'ItemList',itemListElement:rows.map((a,i)=>({'@type':'ListItem',position:i+1,url:origin+'/articles/'+enc(a.slug),name:a.title||a.slug}))}};const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(h.title)} | كوبونات نون</title><meta name="description" content="${esc(h.description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${esc(canonical)}"><script type="application/ld+json">${safe(schema)}</script><style>${PAGE_CSS}</style></head><body><header class="hero"><div class="w"><h1>${esc(h.title)}</h1><p>${esc(h.description)}</p></div></header><main class="w">${searchForm()}${nav()}<section class="grid">${rows.map(card).join('')}</section></main></body></html>`;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=60,s-maxage=300','x-topic-hub':'v5'}})}
function commercePaths(){const out=[];for(const m of Object.keys(MARKETS)){out.push(`/${m}/categories`);for(const k of Object.keys(CATS))out.push(`/${m}/category/${k}`);for(const k of Object.keys(BRANDS))out.push(`/${m}/brand/${k}`);for(const k of Object.keys(COMPS))out.push(`/${m}/compare/${k}`)}return out}
export function topicSitemap(origin){const urls=[...Object.keys(HUBS),...commercePaths()].map(p=>`<url><loc>${origin}${p}</loc></url>`).join('');return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`,{headers:{'content-type':'application/xml; charset=utf-8'}})}
export function augmentWithTopicSitemap(path,xml,origin){if(path==='/sitemap.xml'&&!xml.includes('/sitemap-topics.xml')&&/<\/sitemapindex>/i.test(xml))return xml.replace(/<\/sitemapindex>/i,`<sitemap><loc>${origin}/sitemap-topics.xml</loc></sitemap></sitemapindex>`);return xml}
export function topicNavHtml(){const ks=['mobiles','electronics','computers','home-kitchen','beauty','women-fashion','sports','automotive'];return `<section id="premium-topic-hubs" style="padding:28px 0;background:#f8fafc"><div style="width:min(1180px,92%);margin:auto"><h2>استكشف حسب الهدف أو القسم</h2>${searchForm()}${nav()}<div class="chips"><a href="/saudi/categories">أقسام نون السعودية</a><a href="/uae/categories">أقسام نون الإمارات</a>${ks.map(k=>`<a href="/saudi/category/${k}">${esc(CATS[k].label)}</a>`).join('')}</div></div></section>`}
export const TOPIC_HUB_INFO={version:5,routes:Object.keys(HUBS),commerceRoutes:commercePaths().length,categories:Object.keys(CATS).length,mobileBrands:Object.keys(BRANDS).length,comparisons:Object.keys(COMPS).length,search:'/topics/search/:query',arabicSearch:ARABIC_SEARCH_INFO.version,architecture:'market-category-brand-comparison-article'};
