const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const enc=s=>encodeURI(String(s||''));
const HUBS={
'/topics/buying-guides':{title:'أدلة شراء نون',description:'أدلة عملية لاختيار المنتجات على نون ومراجعة القرار قبل الدفع.',intents:['decision','smartbuy','budget','checklist']},
'/topics/coupon-help':{title:'حل مشاكل كوبونات نون',description:'استخدام الكوبون وأسباب رفض الكود وشروط الأهلية.',intents:['trouble','eligibility','howto','question','timing']},
'/topics/price-and-cart':{title:'السعر والسلة على نون',description:'مقارنة الأسعار وحساب الإجمالي والتوفير قبل الدفع.',intents:['compare','finalprice','value','cart','multi']},
'/topics/returns-and-warranty':{title:'الإرجاع والضمان والبائع',description:'مراجعة البائع والإرجاع والضمان قبل الشراء.',intents:['returns','warranty','seller']},
'/topics/saudi':{title:'أدلة نون السعودية',description:'أحدث الأدلة المخصصة لسوق نون السعودية.',country:'SA'},
'/topics/uae':{title:'أدلة نون الإمارات',description:'أحدث الأدلة المخصصة لسوق نون الإمارات.',country:'AE'}
};
async function latest(env){try{const o=await env.CONTENT_FINAL?.get('bulk/latest.json');return o?await o.json():{articles:[]}}catch{return {articles:[]}}}
const match=(h,a)=>a?.slug&&a.indexable!==false&&(!h.country||a.country===h.country)&&(!h.intents||h.intents.includes(a.intent));
const nav=()=>`<nav class="hub-tabs"><a href="/topics/buying-guides">أدلة الشراء</a><a href="/topics/coupon-help">مشاكل الكوبونات</a><a href="/topics/price-and-cart">السعر والسلة</a><a href="/topics/returns-and-warranty">الإرجاع والضمان</a><a href="/topics/saudi">السعودية</a><a href="/topics/uae">الإمارات</a></nav>`;
function card(a){const market=a.country==='AE'?'الإمارات':'السعودية';return `<article><small>${esc(market)} · ${esc(a.intentLabel||a.intent||'دليل')}</small><h2><a href="/articles/${enc(a.slug)}">${esc(a.title||a.primaryKeyword||a.slug)}</a></h2><p>${esc((a.metaDescription||'').slice(0,180))}</p><a class="read" href="/articles/${enc(a.slug)}">اقرأ الدليل ←</a></article>`}
export function topicHubForArticle(a={}){if(a.country==='AE'&&['coupon','howto','trouble','question','eligibility','timing'].includes(a.intent))return {path:'/topics/coupon-help',...HUBS['/topics/coupon-help']};if(a.country==='SA'&&['coupon','howto','trouble','question','eligibility','timing'].includes(a.intent))return {path:'/topics/coupon-help',...HUBS['/topics/coupon-help']};for(const [path,h] of Object.entries(HUBS)){if(h.intents?.includes(a.intent))return {path,...h}}const path=a.country==='AE'?'/topics/uae':'/topics/saudi';return {path,...HUBS[path]}}
export function articleTopicPathHtml(a={}){const h=topicHubForArticle(a),marketPath=a.country==='AE'?'/topics/uae':'/topics/saudi',market=a.country==='AE'?'نون الإمارات':'نون السعودية';return `<section id="article-topic-path" aria-label="مسار هذا الدليل"><div class="article-topic-path-inner"><p class="article-topic-kicker">تابع نفس الموضوع</p><h2>${esc(h.title)}</h2><p>${esc(h.description)}</p><div class="article-topic-actions"><a href="${h.path}">كل الأدلة في هذا الموضوع</a><a href="${marketPath}">${esc(market)}</a><a href="/blog">أحدث المقالات</a></div></div></section>`}
export async function topicLanding(path,origin,env){const h=HUBS[path];if(!h)return null;const data=await latest(env),rows=(data.articles||[]).filter(a=>match(h,a)).slice(0,24),canonical=origin+path;const schema={'@context':'https://schema.org','@type':'CollectionPage',name:h.title,url:canonical,description:h.description,mainEntity:{'@type':'ItemList',itemListElement:rows.map((a,i)=>({'@type':'ListItem',position:i+1,url:origin+'/articles/'+enc(a.slug),name:a.title||a.slug}))}};const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(h.title)} | كوبونات نون</title><meta name="description" content="${esc(h.description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${esc(canonical)}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><style>body{margin:0;font-family:Tahoma,Arial,sans-serif;background:#f8fafc;color:#111827}.w{width:min(1180px,92%);margin:auto}.hero{background:#111827;color:#fff;padding:42px 0}.hero p{color:#d1d5db;line-height:1.9}.hub-tabs{display:flex;gap:8px;overflow:auto;padding:18px 0}.hub-tabs a{white-space:nowrap;background:#fff;border:1px solid #e5e7eb;padding:9px 12px;border-radius:999px;text-decoration:none;color:#111827;font-weight:800}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding-bottom:50px}.grid article{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:18px}.grid h2{font-size:20px;line-height:1.6}.grid p{color:#667085;line-height:1.8}.grid a{text-decoration:none;color:#111827}.read{color:#6d28d9!important;font-weight:900}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:640px){.grid{grid-template-columns:1fr}}</style></head><body><header class="hero"><div class="w"><a href="/" style="color:#fff">← كوبونات نون</a><h1>${esc(h.title)}</h1><p>${esc(h.description)}</p></div></header><main class="w">${nav()}<section class="grid">${rows.map(card).join('')}</section></main></body></html>`;return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public,max-age=60,s-maxage=300','x-topic-hub':'v2'}})}
export function topicSitemap(origin){const urls=Object.keys(HUBS).map(p=>`<url><loc>${origin}${p}</loc></url>`).join('');return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`,{headers:{'content-type':'application/xml; charset=utf-8'}})}
export function augmentWithTopicSitemap(path,xml,origin){if(path==='/sitemap.xml'&&!xml.includes('/sitemap-topics.xml')&&/<\/sitemapindex>/i.test(xml))return xml.replace(/<\/sitemapindex>/i,`<sitemap><loc>${origin}/sitemap-topics.xml</loc></sitemap></sitemapindex>`);return xml}
export function topicNavHtml(){return `<section id="premium-topic-hubs" style="padding:28px 0;background:#f8fafc"><div style="width:min(1180px,92%);margin:auto"><h2>استكشف حسب هدفك</h2>${nav()}</div></section>`}
export const TOPIC_HUB_INFO={version:2,routes:Object.keys(HUBS)};
